repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # укажи актуальную версию ruff
    hooks:
      - id: ruff
        args: [--fix]   # чтобы сразу автофиксить по возможности
      - id: ruff-format
